version: '3.8'

services:
  openfga:
    image: openfga/openfga:latest
    container_name: patunay-openfga
    command: run
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgresql://postgres:postgres@postgres:5432/openfga?sslmode=disable
      - OPENFGA_LOG_LEVEL=debug
      - OPENFGA_HTTP_ADDR=0.0.0.0:8080
      - OPENFGA_GRPC_ADDR=0.0.0.0:8081
    ports:
      - "8080:8080"
      - "8081:8081"
      - "3000:3000" # Playground
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - patunay-network

  postgres:
    image: postgres:15
    container_name: patunay-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=openfga
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - patunay-network

volumes:
  postgres_data:

networks:
  patunay-network:
    driver: bridge